### PR TITLE
assignment files

### LINKED ISSUE #1: Port and Divide Dataset, Augmentations, DataLoader Assignment
## Description
Divide the Spring 2023 CS 175: Projects in AI Dataset, Augmentations, Load homework assignment into the custom Dataset and Augmentations component for public use. Not that this is the structure of the assignment and that the solutions are not provided.

## Files
- [  ] bps_dataset.py
- [  ] augmentation.py
- [  ] test cases
- [  ] github actions workflow
- [  ] README
- [  ] LICENSE

## Tests
- [  ] test_bps_dataset.py
- [  ] test_augmentations.py

## Tasks
Port all necessary files.

### PR DESCRIPTION
**Pull request by nadia-eecs**
## Description
Introduction of assignment files for custom PyTorch Dataset, Augmentations, and DataLoader from Spring 2023 CS 175 Projects in AI Assignment.

## Type of Change
- [  ] Enhancement: Improved version of the original assignment for public use.

## Tests
Test classes and member functions using `unittest`
- [  ] `test_bps_augmentations.py`
- [  ] `test_bps_dataset_class.py`
 
## Files
- `README.md`
- `LICENSE`
- `.github/workflows/custom_dataset_dataloader_transforms.yml`
- `custom_dataset_dataloader_transforms/augmentations.py`
- `custom_dataset_dataloader_transforms/bps_dataset.py`
- `tests/test_bps_augmentations.py`
- `tests/test_bps_dataset_class.py`

closes #1

### CODE REVIEW

**Comment by nadia-eecs** [comment]
@campjake Please double check to make sure I put the correct paths :wink:

**Comment by CakeJamble** [comment]
Should we add a definition and test for `ToThreeChannels`?

**Comment by nadia-eecs** [comment]
@campjake, i was going to save `ToThreeChannels` for transfer learning w/ pretrained weights since we don't need it for this earlier assignment. What do you think?

**Comment by CakeJamble** [comment]
That makes more sense. I just remembered that you've explained your reasoning before, so thanks for the reminder 😆 

The paths and templates look good! 👍  I'll submit my formal review later today (7/5)

**Review by CakeJamble — APPROVED** [review]
Looks good! 👍

**Comment by nadia-eecs** [comment]
merge refactored assignment to main.

**Pull request merged**
